version: '3.3'

services:

  prometheus:
    image: mfurquim/prometheus:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        scrapeinterval: 30s
        evaluationinterval: 15s
        scrapetimeout: 10s
        tsdbretention: 3d
        targetsfile: ./targets.json
        rulespath: rules
        alertspath: alerts
        scheme: http
        metricspaths: /metrics,/metrics-http,/metrics-negocio
        startupfile: startup.sh
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus

  generator:
    image: mfurquim/metrics-generator:v0.0.1
    build: ./metrics_generator/
    ports:
      - 3000:3000

volumes:
  prometheus:

