# http_pending_requests
# http_requests_device_total
# http_requests_app_total
# http_responses_sent
# http_requests_received
# http_requests_duration_seconds_count
# http_requests_duration_seconds_sum

groups:
- name: aggr_global_http_per_server
  rules:
  - record: http_pending_requests_sum:sum_irate
    expr: sum(irate(http_pending_requests{job!="$REGION"}[1m])) without (job)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_requests_device_total:sum_irate
    expr: sum(irate(http_requests_device_total{job!="$REGION"}[1m])) without (job, device_os_version)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_requests_app_total:sum_irate
    expr: sum(irate(http_requests_app_total{job!="$REGION"}[1m])) without (job)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_responses_sent:sum_irate
    expr: sum(irate(http_responses_sent{job!="$REGION"}[1m])) without (job)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_requests_received:sum_irate
    expr: sum(irate(http_requests_received{job!="$REGION"}[1m])) without (job)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_requests_duration_seconds_count:sum_irate
    expr: sum(irate(http_requests_duration_seconds_count{job!="$REGION"}[1m])) without (job, device_major_version)
    labels:
      statistics: per_server_global_http
      job: $REGION

  - record: http_requests_duration_seconds_sum:sum_irate
    expr: sum(irate(http_requests_duration_seconds_sum{job!="$REGION"}[1m])) without (job, device_major_version)
    labels:
      statistics: per_server_global_http
      job: $REGION